apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oc-pipelines-oc-final
spec:
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
    - name: git-clone
      taskRef:
        name: git-clone
      runAfter: [cleanup]
    - name: flake8
      taskRef:
        name: flake8
      runAfter: [git-clone]
    - name: nose
      taskRef:
        name: nose
      runAfter: [flake8]
    - name: buildah
      taskRef:
        name: buildah
      runAfter: [nose]
    - name: deploy
      taskRef:
        name: openshift-client
      runAfter: [buildah]
